### ISSUE TITLE
Are child products with multiple parents skipped here? 

### ISSUE THREAD

**Issue by seansan** [magmodules/magento1-channable#23]
Are child products with multiple parents skipped here? 

The module supports multiple parents everywhere - only here we loop over the array and instead of exporting every parent we are only using the last parent (and thereby ignoring the others, data is lost)

https://github.com/magmodules/magento1-channable/blob/39ac8595a7796093d50822e0cb6205240e286de2/app/code/community/Magmodules/Channable/Model/Channable.php#L374

Would it not be a good idea to add the loop around the feed generation block and thus support multiple parent relations?

**Comment by seansan** [comment]
By adding the export in the loop the export does work. One 'possible' problem could be that the same ID is sent multiple times (because a child now occurs multiple time in the feed, once for every parent relation)

**Comment by Marvin-Magmodules** [comment]
No not skipped, but the first one is taken. Not sure what you like to accomplish by looping though multiple parents for the simple product as also the parent is added to the feed. Sending duplicate ID's is a no go and also adding multiple values for the same simple product does not make it a lot easier down the road (Feed > Channable > Price Comparison/Marketplace party). 

Is you have a solution or a valid case where this is supported on Price Comparison/Marketplace let me know.

**Comment by seansan** [comment]
This does solve the problem and adds multiple parents x multiple children (N:N instead of N:1)

However the id appears (as a child multiple times) one would have to add a multipack column to for, for example merrchant https://support.google.com/merchants/answer/6324488?hl=en

    public function getFeedData($products, $parents, $config, $parentAttributes, $prices, $parentRelations)
    {
        $feed = array();

        foreach ($products as $product) {
            $parent = null;
            if (!empty($parentRelations[$product->getEntityId()])) {
                foreach ($parentRelations[$product->getEntityId()] as $parentId) {
                    if ($parent = $parents->getItemById($parentId)) {

                        $productData = $this->helper->getProductDataRow($product, $config, $parent, $parentAttributes);
                        if ($productData) {
                            $productRow = array();
                            foreach ($productData as $key => $value) {
                                if (!is_array($value)) {
                                    $productRow[$key] = $value;
                                }
                            }

                            if ($extraData = $this->getExtraDataFields($productData, $config, $product, $prices)) {
                                $productRow = array_merge($productRow, $extraData);
                            }

                            $productRow = new Varien_Object($productRow);
                            $productRow = $productRow->getData();

                            $feed[] = $productRow;
                            if ($config['item_updates']) {
                                $this->processItemUpdates($productRow, $config['store_id']);
                            }

                            unset($productRow);
                        }

                    }
                }
            }


        }

        return $feed;
    }

**Comment by Marvin-Magmodules** [comment]
multipack = identical products in 1 grouped product. Also this will add the simple product in the feed multiple times, so you will have duplicate ID's,SKU's,EAN's etc. This will give you issues down the road. But please feel free to try this, but we won't add this to the module.

**Comment by seansan** [comment]
See below

>> No not skipped, but the first one is taken
is it not the last one? (until the lasst contine and that $parent variable
is set and used)

>> Is you have a solution or a valid case where this is supported on Price
Comparison/Marketplace let me know.

Shopping supports multipack
https://support.google.com/merchants/answer/6324488?hl=en where a product
can be added to the feed more than once (red. bubdle = for different
products)

The data would look like below



id  : item_group_id :          sku            : multipack      : GTIN

1         ""               1PACK-WHITE             1

10        1                white-small                           1233456

11        1                white-large                           445566

2         ""               2PACK-WHITE             2

10        2                white-small
1233456

11        2                white-large                           445566



As a result the *id* is not unique. But the combination of *parent_id* and
*id* would be unique


[image: image.png]

**Comment by Marvin-Magmodules** [comment]
Also the combination of parent_id and id is not per se unique and it will add the same product multiple times in the feed. This has a big impact and still not sure how this handles down the road to the marketplaces. We can look into this for Magento 2, but decided not to implement this new type of a feature for Magento 1.

**Comment by seansan** [comment]
>> Also the combination of parent_id and id is not per se unique and it
will add the same product multiple times in the feed.

This is correct

However it should be seen in combination with an "mutlitpack" attribute
which then does make it unique

So normally these would be counted as the same because they have the same
EAN

id:1 ean:123 size:xl multipack:3
id:2 ean:123 size:xl multipack:6

But multipack is also considerd by Google and thus these products are seen
ass 2 unique

https://support.google.com/merchants/answer/6324488?hl=en

I would suggest this to be a setting becuase I agree that not all business
have multipacks .... but in fashion it is quite common

Hope it helps

**Comment by Marvin-Magmodules** [comment]
Hi @seansan drop me an email, so we can look into this to check if this is feasible to implement on Magento 2.
