### ISSUE TITLE
Would it be an idea to create a setting for this (and other events)

### ISSUE THREAD

**Issue by seansan** [magmodules/magento1-channable#24]
If setting generate events = true then generate

When exporting 100k to 1mio+ lines of data this can maybe have an performance impact

If not used: then maybe it can be turned off

https://github.com/magmodules/magento1-channable/blob/39ac8595a7796093d50822e0cb6205240e286de2/app/code/community/Magmodules/Channable/Model/Channable.php#L393

**Comment by Marvin-Magmodules** [comment]
Hi @seansan Did some testing, but was not able to find any noticeable performance impact. Closing this issue now, but please feel free to reopen the issue if you encounter performance impact from this.
