### ISSUE TITLE
Select attribute that has no value exported to Channable as False (instead of empty)

### ISSUE THREAD

**Issue by seansan** [magmodules/magento1-channable#25]
We have the problem where

Select attribute that has no value exported to Channable as False (we would expect: empty)

Situation
- Select product attribute
- No value set for product (does not apply)

Actual
- Attribute exported with value False

Expected
- Attribute exported as empty (or empty string or null)

![image](https://user-images.githubusercontent.com/652395/60025066-31bad000-9699-11e9-843c-533b38006fbf.png)

**Comment by Marvin-Magmodules** [comment]
Fixed in [v1.6.12](https://github.com/magmodules/magento1-channable/releases/tag/v1.6.12)
