### ISSUE TITLE
Can not install extension through composer.json by tag

### ISSUE THREAD

**Issue by mediactbv** [magmodules/magento1-channable#4]
I see you added a composer.json to the master branch after the release of v1.5.3, however you didn't place a new tag on the master branch. We can therefor now only install a specific release by use of: dev-master#7992fefd2dc21590ca964e48cc6fe5e2ccea6755 as 1.5.3 and not just ^1.5.3.

You also use a version constraint in the composer.json. Can you remove the tag from the composer.json file and re-tag the master with 1.5.4? Otherwise composer will use the version constraint in the composer.json file.

**Comment by Marvin-Magmodules** [comment]
Yes, removed the version tag from the composer.json file, https://github.com/magmodules/magento1-channable/releases/tag/v1.5.5
